/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Mobile mobile = new Mobile();
        Mobile iphone = new Iphone();
        Mobile android = new Android();
        mobile.call("fghfghfghfghfghfghfhfhfhfghfhsdgdgdgdfgdfgdfg");
        iphone.call("sdf");
        android.call("sdffff");

        Person person = new Person();
        person.setName("Ken");
        person.setMobile(iphone);
        person.makeCall();

        IphoneRobot robot = new IphoneRobot();
        Iphone otherIphone = new Iphone();
        robot.setIphone(otherIphone);
        robot.makeCall();
    }
}
