/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Mobile mobile = new Mobile();
        Mobile iphone = new Iphone();
        Mobile android = new Android();
        mobile.call("boss billy");
        iphone.call("boss billy");
        android.call("boss billy");
    }
}
